import type { ProductDetail, Variante } from '@/types'
export type { Variante, ProductDetail }

export const PRODUCTOS_MOCK: Record<string, ProductDetail> = {
  'pulsera-charm-dorada': {
    id: 'pul-001',
    slug: 'pulsera-charm-dorada',
    nombre: 'Pulsera Charm Dorada',
    descripcion_corta: 'Baño oro 18k · Dije incluido · Resistente al agua',
    descripcion: 'La más querida de nuestra colección. Cadena snake bañada en oro 18k de alta durabilidad, cierre langosta y dije intercambiable incluido. Perfecta para llevar sola o en conjunto.',
    precio: 18990,
    material: 'Baño oro 18k de alta durabilidad · Resistente al agua',
    badge: 'Más vendido',
    badge_variant: 'default',
    categoria: 'Pulseras',
    categoria_slug: 'pulseras',
    variantes: [
      { id: 'pul-001-s',  nombre: 'S — 16 cm', stock: 24 },
      { id: 'pul-001-m',  nombre: 'M — 17 cm', stock: 18 },
      { id: 'pul-001-l',  nombre: 'L — 18 cm', stock: 9 },
      { id: 'pul-001-xl', nombre: 'XL — 19 cm', stock: 6 },
    ],
  },
  'pulsera-snake-fina': {
    id: 'pul-002',
    slug: 'pulsera-snake-fina',
    nombre: 'Pulsera Snake Fina',
    descripcion_corta: 'Cadena snake · Baño oro 18k · Cierre langosta',
    descripcion: 'Elegancia minimalista. Cadena snake ultra fina bañada en oro 18k con cierre langosta dorado. Un básico que va con todo.',
    precio: 14990,
    material: 'Baño oro 18k · Cierre langosta',
    categoria: 'Pulseras',
    categoria_slug: 'pulseras',
    variantes: [
      { id: 'pul-002-s',  nombre: 'S — 16 cm', stock: 8 },
      { id: 'pul-002-m',  nombre: 'M — 17 cm', stock: 5 },
      { id: 'pul-002-l',  nombre: 'L — 18 cm', stock: 3 },
      { id: 'pul-002-xl', nombre: 'XL — 19 cm', stock: 2 },
    ],
  },
  'pulsera-eslabones': {
    id: 'pul-003',
    slug: 'pulsera-eslabones',
    nombre: 'Pulsera Eslabones',
    descripcion_corta: 'Eslabones cuadrados · Baño oro 18k · Largo ajustable',
    descripcion: 'Tendencia statement. Eslabones cuadrados bañados en oro 18k con largo ajustable mediante extensión de 3 cm. Presencia y elegancia en una sola pieza.',
    precio: 16990,
    material: 'Baño oro 18k · Extensión incluida',
    badge: 'Nuevo',
    badge_variant: 'default',
    categoria: 'Pulseras',
    categoria_slug: 'pulseras',
    variantes: [
      { id: 'pul-003-s',  nombre: 'S — 16 cm', stock: 0 },
      { id: 'pul-003-m',  nombre: 'M — 17 cm', stock: 0 },
      { id: 'pul-003-l',  nombre: 'L — 18 cm', stock: 0 },
      { id: 'pul-003-xl', nombre: 'XL — 19 cm', stock: 0 },
    ],
  },
}